name: emg3d-gallery

channels:
  - conda-forge

dependencies:
  - "libblas=*=*mkl"
  - emg3d>=1.8.3
  - xarray
  - discretize
  - h5py
  - matplotlib
  - scooby
  - sphinx>=7.3
  - sphinx-gallery>=0.16
  - numpydoc
  - pooch
  - sphinx-design
  - pydata-sphinx-theme
  - mkl-service
  - tqdm
  - memory_profiler
