name: emg3d-gallery

channels:
  - conda-forge
  - gimli

dependencies:
  - "libblas=*=*mkl"
  - empymod
  - emg3d
  - xarray
  - discretize
  - h5py
  - matplotlib
  - scooby
  - sphinx
  - sphinx-gallery
  - numpydoc
  - pooch
  - sphinx-design
  - pydata-sphinx-theme
  - mkl-service
  - tqdm
  - memory_profiler
  - pygimli
